# Site settings
title: KDee
email: kirkdaniels@me.com
description: "kdee website"
baseurl: ""
url: "http://localhost:4000"
version: 1.0

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, Gruntfile.js, package.json, 'node_modules', '*.esproj']